name: Build Main
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: 1.25
      - name: Install dependencies
        run: make install-deps
      - name: Lint
        run: make lint
      - name: Build
        run: make
